runtime: custom
env: flex
service: default

vm_health_check:
  enable_health_check: False

handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

manual_scaling:
  instances: 1
