version: 2
jobs:
  build-front:
    working_directory: ~/project/rao-front
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm rebuild node-sass
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - rao-front/dist
  
  deploy-front:
    working_directory: ~/project/rao-front
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: mv dist www
      - run: gcloud app deploy --promote --stop-previous-version

  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - checkout
      - run: ./deploy-appengine/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-front
      - deploy-front:
          requires:
            - build-front
          filters:
            branches:
              only:
                - less-expensive
  common:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
