version: 2
jobs:

  install-front-end-dependencies:
    working_directory: ~/project/rao-front
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-npm-dependencies-{{ checksum "package.json" }}
            - v1-npm-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - rao-front/node_modules

  lint-front-end:
    working_directory: ~/project/rao-front
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: npm run lint

  build-front-end:
    working_directory: ~/project/rao-front
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: ~/project
      - run: npm rebuild node-sass
      - run: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - rao-front/dist
  
  build-back-end:
    working_directory: /go/src/github.com/Zenika/rao/rao-back
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout:
          path: /go/src/github.com/Zenika/rao
      - run: CGO_ENABLED=0 GOOS=linux go build -o ./rao
      - run: cp -R ./rao ~/project/rao-back/dist
      - persist_to_workspace:
          root: ~/project
          paths:
            - rao-back/dist
  
  deploy:
    docker:
      - image: google/cloud-sdk:203.0.0
    environment:
      GCLOUD_PROJECT: grao-199314
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: mkdir ~/deploy-rao-front
      - run: cp rao-front/app.yaml ~/deploy-rao-front/app.yaml
      - run: cp -R rao-front/dist ~/deploy-rao-front/www
      - run: envsubst < rao-back/app.yaml > rao-back/app.deploy.yaml
      - run: echo ${GCLOUD_SERVICE_KEY} | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project ${GCLOUD_PROJECT}
      - run: gcloud app deploy dispatch.yaml rao-back/rao-back/app.deploy.yaml ~/deploy-rao-front/app.yaml --promote --stop-previous-version

  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - checkout
      - run: ./deploy-appengine/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-front-end-dependencies
      - lint-front-end:
          requires:
            - install-front-end-dependencies
      - build-front-end:
          requires:
            - install-front-end-dependencies
      - build-back-end
      - deploy:
          requires:
            - lint-front-end
            - build-front-end
            - build-back-end
          filters:
            branches:
              only:
                - master
                - back-app-engine-standard

  common:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
