version: "3"
services:
  docconv:
    build: ./docconv
    ports: 
      - "8888:8888"
    networks: 
      - rao
  raoback:
    build: ./raoback
    ports: 
      - "8080:8080"
    networks: 
      - rao
    environment:
      - GRAO_APP_PORT=8080
      - GRAO_DBX_KEY=dropbox_key
      - GRAO_DBX_SECRET=dropbox_secret
      - GRAO_DBX_TOKEN=dropbox_token
      - GRAO_DBX_ROOT=dropbox_root_path
      - GRAO_DBX_CURSOR=cursor_file
      - GRAO_ALGOLIA_ID=BO714R0OR9
      - GRAO_ALGOLIA_KEY=7a425cae047fc1c8f7a5d13d804265ba
      - GRAO_LOG_FILE=/tmp/rao.log
      - GRAO_LOG_LEVEL=DEBUG
      - GRAO_POLL_EVERY=@daily
      - RAO_POLL_FROM=rao_filter_regexp_string
      - BDC_POLL_FROM=bdc_filter_regexp_string
      - AUTH0_AUDIENCE=https://zenika.grao.com/test/v1
      - AUTH0_DOMAIN=zenika.eu.auth0.com
      - AUTH0_JWKS_URI=https://zenika.eu.auth0.com/.well-known/jwks.json
      - AUTH0_ISSUER=https://zenika.eu.auth0.com/
  raofront:
    image: nginx
    volumes: 
      - ./dist:/usr/share/nginx/html
    networks: 
      - rao
    ports: 
      - "80:80"
networks: 
  rao: