version: "3"
services:
  docconv:
    image: zenika/rao-docconv:v1
    networks: 
      - rao
  raoback:
    image: zenika/grao-back:v1
    networks: 
      - rao
  raofront:
    image: zenika/rao-front:v1.02
    networks: 
      - rao
    ports:
      - 80:80
networks: 
  rao:
