service: back
runtime: go
api_version: go1

handlers:
  - url: /api/v1/poll
    script: _go_app
    login: admin
  - url: /.*
    script: _go_app
 
env_variables:
  GRAO_APP_PORT: "8080"
  GRAO_DBX_KEY: "${GRAO_DBX_KEY}"
  GRAO_DBX_SECRET: "${GRAO_DBX_SECRET}"
  GRAO_DBX_TOKEN: "${GRAO_DBX_TOKEN}"
  GRAO_DBX_ROOT: "Zenika - Clients"
  GRAO_DBX_CURSOR: "cursor"
  GRAO_ALGOLIA_ID: "${GRAO_ALGOLIA_ID}"
  GRAO_ALGOLIA_KEY: "${GRAO_ALGOLIA_KEY}"
  GRAO_LOG_FILE: "/var/log/app_engine/app.log"
  GRAO_LOG_LEVEL: "DEBUG"
  RAO_POLL_FROM: "(?i)^.+/_{1,2}clients(_|\\s){1}(?P<Agence>[\\w&\\s]+)/(?P<Client>[^/]+)/(?P<Projet>[^/]+)/REPONSE ENVOYEE"
  BDC_POLL_FROM: "(?i)^.+/_{1,2}clients(_|\\s){1}(?P<Agence>[\\w&\\s]+)/(?P<Client>[^/]+)/(?P<Projet>[^/]+)/BON DE COMMANDE/(?P<Consultant>[^/]+)"
  AUTH0_AUDIENCE: "https://grao.zenika.com/api/v1"
  AUTH0_DOMAIN: "zenika.eu.auth0.com"
  AUTH0_JWKS_URI: "https://zenika.eu.auth0.com/.well-known/jwks.json"
  AUTH0_ISSUER: "https://zenika.eu.auth0.com/"
  DOCD_PORT: "80"
  DOCD_HOST: "docd.grao-199314.appspot.com"
