runtime: custom
env: flex
service: docd

vm_health_check:
  enable_health_check: False
 
handlers:
- url: /.*
  script: this field is required, but ignored

resources:
  cpu: .5
  memory_gb: 1
  disk_size_gb: 10

manual_scaling:
  instances: 1
